sudo: required
dist: bionic
languagem: csharp
mono: none
dotnet: 5.0
services: docker

script:
  - docker-compose build

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: 
    docker tag rest-with-asp-net-db:$TRAVIS_JOB_ID DOCKER_USERNAME/rest-with-asp-net-db:$TRAVIS_JOB_ID;
    docker tag rest-with-asp-net:$TRAVIS_JOB_ID DOCKER_USERNAME/rest-with-asp-net:$TRAVIS_JOB_ID;
    docker push DOCKER_USERNAME/rest-with-asp-net:$TRAVIS_JOB_ID;
    docker push DOCKER_USERNAME/rest-with-asp-net-db:$TRAVIS_JOB_ID;
  on:
    branch: master
notifications:
  email: false
