
  
version: '3.4'

services:
  db:
    image: rest-with-asp-net-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: /home/iara/C#/RESTApi/dbDocker/DockerFile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_ASPNET
    ports:
      - "3308:3306"
    networks:
      - udemy-network
      
  rest-with-asp-net:
    image: rest-with-asp-net
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
    